version: 2
jobs:
  build:
    docker:
      - image: vuejs/ci

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-

      - run:
          name: Install Dependencies
          command: yarn --frozen-lockfile

      - save_cache:
          paths:
            - node_modules
            - ~/.cache/yarn
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: Run Tests
          command: yarn test --ci --runInBand

      - run:
          name: Test d.ts
          command: yarn test-dts

      - run:
          name: Check size
          command: yarn size
